name: Download CDN CIDR and Commit git

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 17 * * *" # 北京时间凌晨1点执行
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check directory exists
        run: |
          if [ ! -d "./cidr" ]; then
            mkdir ./cidr
          fi
        
      - name: Install curl
        run: sudo apt-get install -y curl
        
      - name: Down Gcore cdn cidr
        run: |
          # curl --raw -o ./cidr/gcore.json https://api.gcorelabs.com/cdn/public-net-list
            curl --raw -o ./cidr/gcore.json https://api.gcore.com/cdn/public-ip-list
          
      - name: Down cloudfront cdn cidr
        run: |
          curl --raw -o ./cidr/cloudfront.json https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips
          
      - name: Down cloudflare cdn cidr
        run: |
          curl --raw -o ./cidr/cloudflare-ipv4.json https://www.cloudflare.com/ips-v4
          curl --raw -o ./cidr/cloudflare-ipv6.json https://www.cloudflare.com/ips-v6
          
      # https://github.com/marketplace/actions/up2qn-action
      - name: update to qiniu oss   
        uses: luochongfei/up2qn@master
        with:
          bucket: wechaty
          zone: 华东
          access_key: ${{ secrets.QINIU_AK }}
          secret_key: ${{secrets.QINIU_SK }}
          local_dir: ./cidr
          target_dir: /CDNProxy
        
          
      - name: Commit changes
        # if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.name "github_job"
          git config --global user.email "jesn2013@hotmail.com"
          git add .
          git commit -m "update cdn cidr"
          git push
