name: Download CDN CIDR and Commit git

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check directory exists
        run: |
          if [ ! -d "./cidr" ]; then
            mkdir ./cidr
          fi
        
      - name: Install curl
        run: sudo apt-get install -y curl
        
      - name: Down Gcore cdn cidr
        run: |
          curl --raw -o ./cidr/gcore.json https://api.gcorelabs.com/cdn/public-net-list
          
      - name: Commit changes
        run: |
          git config --global user.name "github_job"
          git config --global user.email "jesn2013@hotmail.com"
          git add .
          git commit -m "update cdn cidr"
          git push
